name: release
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 10 * * *'
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: jellyfin/jellyfin-ffmpeg
          path: jf
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: loeken/docker-jellyfin
          path: docker-jf
      - name: ls
        run: cp docker-jf/Dockerfile jf/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          push: true
          tags: loeken/jellyfin:10.11.10,loeken/jellyfin:latest
          context: ./jf
          no-cache: true
